

def write_yaml(title:str, msg:str = None, imgPaths:List[Dict] = None, filePaths:List[Dict] = None,
               timer:int = TIMER_OFF, mailbox:str = "") -> None: ...

def read_yaml(path:str) -> Dict: ...

def change_yaml(path:str, dct:Dict, node:str) -> None: ...

def add_yaml(path:str, dct:Dict, node:str) -> None: ...

class SetProcess:
    def __init__(self, title:str) -> None: ...

    def configer(self, mag:str = None, imgPaths:List[Dict] = None, filePaths:List[Dict] = None,
                 timer:int = TIMER_OFF, mailbox:str = "") -> None: ...

    def set_epoch(self, now:int, total:int) -> None: ...

    def change_node(self, dct:Dict, node:str) -> None: ...

    def add_node(self, dct:Dict, node:str) -> None: ...
