def rd_yaml(path:str) -> None: ...

def _gen_msg(conf:Dict, status:int) -> (str, str): ...

class Supervisor:
    def __init__(self) -> None: ...

    def _find_process(self) -> Dict: ...

    def _get_fin_process(self) -> Dict: ...

    def _send_mails(self, procs:Dict, isTimer:int) -> None: ...

    def _timer_func(self, num:int) -> None: ...

    def supervise(self) -> None: ...