from typing import List, Dict
from smtplib import SMTP
from email.mime.nonmultipart import MIMENonMultipart

class MailDraft:
    IMG_EXT = None
    LINE_LENGTH = None
    def __init__(self, title: str, sender: str, receivers: List[str], msg: str, attachments: List[str]):
        self.title = None
        self.sender = None
        self.receivers = None
        self.msg = None
        self.attachments = None
    def send_draft(self, smtpObj: SMTP): ...
    def add_msg(self, newMsg: str): ...
    def add_file(self, newFileLst: List[str]): ...
    def _check_path(self, path: str) -> List[MIMENonMultipart]: ...
    def _make_img(self, imgPath: str, imgName: str): ...
    def _make_file(self, fPath: str, fName: str): ...
    def _sep_line(self, sentence: str) -> str: ...
    def _fill_line(self, sentence: str) -> str: ...
    def _cal_strlen(self, sentence: str) -> int: ...

class MailBox:
    def __init__(self, params: Dict):
        self.smtpObj = None
        self.imapObj = None
        self.draftLst = None
        self.emailLst = None
        self.emailIDLst = None
        self.unreadMailIDLst = None
    def add_draft(self, draft: MailDraft): ...
    def _find_draft_title(self, title: str) -> int: ...
    def list_draft(self): ...
    def send_draft(self, title: str): ...
    def send_all_draft(self): ...
    def _byte2str(self, data: [bytes | str]) -> str: ...
    def get_all_mail(self): ...
    def list_email(self): ...
    def logout(self): ...



