from typing import List

class TextVisualizer:
    def __init__(self, maxLineLength: int, afterLine: str):
        self.maxLineLength = maxLineLength
        self.afterLine = afterLine
    def __call__(self, text: str) -> str: ...
    def _sep_section(self, section: str) -> List[str]: ...
    def _fill_line(self, line: str) -> str: ...
    def _get_word(self, section: str, index: int) -> (str, int, int): ...
    def _cal_strlen(self, sentence: str) -> float: ...
    def _is_Chinese(self, char: str) -> bool: ...