from typing import Dict

class ConfLoader:
    def __init__(self, path: str):
        self.params = None
    def _read(self, path: str) -> Dict: ...
    def _save(self, path: str): ...
    def add(self, **kwargs): ...
