from typing import Dict

class CfgLoader:
    def __init__(self, path: str):
        self.params = None
    def _read(self, path: str) -> Dict: ...
    def _save(self, path: str): ...
    def add(self, **kwargs): ...
    def __getitem__(self, key: str) -> str: ...
